### ISSUE TITLE
issue with using babel-mako extractor?

### ISSUE THREAD

**Issue by tisdall** [wichert/lingua#44]
After updating to 2.5...  (though it also didn't work in 2.4, but gave a different error)

I have a file `lingua.cfg` with contents:

```
[extension:.mako]
plugin = babel-mako

[extension:.pt]
plugin = xml

[extension:.py]
plugin = python
```

Then I try to use `pot-create`:

```
$env/bin/pot-create -c lingua.cfg -d mainserver -o mainserver/locale/mainserver.pot mainserver
Traceback (most recent call last):
  File "env/bin/pot-create", line 11, in <module>
    sys.exit(main())
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/lingua/extract.py", line 218, in main
    read_config(options.config)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/lingua/extract.py", line 154, in read_config
    EXTENSIONS[extension] = EXTRACTORS[plugin](config)
TypeError: wrapper() missing 1 required positional argument: 'options'
```

prior to the update I got:

```
$env/bin/pot-create -c lingua.cfg -d mainserver -o mainserver/locale/mainserver.pot mainserver
Traceback (most recent call last):
  File "env/bin/pot-create", line 11, in <module>
    sys.exit(main())
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/lingua/extract.py", line 250, in main
    catalog.save(options.output)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/polib.py", line 424, in save
    contents = getattr(self, repr_method)()
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/polib.py", line 620, in __unicode__
    return ret + _BaseFile.__unicode__(self)
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/polib.py", line 320, in __unicode__
    ret.append(entry.__unicode__(self.wrapwidth))
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/polib.py", line 956, in __unicode__
    val = getattr(self, c[0])
  File "/sites/metrics_dev/env/lib/python3.4/site-packages/lingua/extract.py", line 45, in comment
    return u'\n'.join(self._comments)
TypeError: sequence item 0: expected str instance, list found
```
